name: "Temperature"
author: "@nicholasbergesen"
description: "The Temperature"
inputs:
  city:
    description: "Where do you want to check the temperature"
    required: true 
  API_KEY:
    description: "Weather API key"
    required: true
outputs:
  temperature:
    description: "The temperature in C"
runs:
  using: "node12"
  main: "main.js"
