name: Build Push Deploy
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo ${{ secrets.ENV_SECRET }}
