name: Temperature
on: [push]
jobs:
  Get-Temp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/
        with:
          city: "Seoul"
          API_KEY: ${{ secrets.WEATHER_API_KEY }}
